config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :users, only: %i[new create] do
    resources :playlists, controller: 'user/playlists', only: %i[index create]
  end
  resource :account, only: :destroy do
    resources :playlists, controller: 'account/playlists', only: :index do
      member { patch :ack, :like }
    end
  end
  resource :session, only: %i[new create destroy]

  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  get 'logout' => 'sessions#destroy'

  scope path: '/:user_id' do
    get '' => 'user/playlists#new', as: :new_playlist
    get 'playlist' => 'user/playlists#index'
    get 'playlist/name' => 'playlists#name', as: :guess_name
  end

  root 'playlists#index'
end

app/models/playlist.rb
class Playlist < ApplicationRecord
  belongs_to :for_user, class_name: 'User', inverse_of: :received_playlists
  belongs_to :from_user, class_name: 'User', inverse_of: :sent_playlists, optional: true
  has_many :tags, dependent: :delete_all, inverse_of: :playlist

  accepts_nested_attributes_for :tags, reject_if: :all_blank

  validates :url,
            presence:   true,
            url:        true,
            uniqueness: {scope: :for_user_id}
  validates :name,
            length:    {maximum: 100},
            allow_nil: true
  validates :description,
            length:    {maximum: 2000},
            allow_nil: true
  validates :priority,
            presence:     true,
            numericality: {greater_than_or_equal_to: 0}

  extend SetNilIfBlank
  set_nil_if_blank :name, :description

  attr_writer :tag_names
  after_save :save_tags

  before_validation { |u| u.url = u.url&.strip }
  before_validation :set_name
  after_create :send_email

  def tag_names(reload: false)
    @tag_names = nil if reload
    @tag_names ||= tags.order('id ASC').map { |t| "##{t.name}" }.join(' ')
  end

  private

  def save_tags
    new_tags = tag_names.scan(/#(\w+)/).flatten
    new_tags.each do |name|
      tags.where(name: name).find_or_create
    end
    tags.delete_by('name NOT IN (?)', new_tags)
  end

  def set_name
    self.name ||= url
  end

  def send_email
    PlaylistMailer.new_playlist(self).deliver_now
  end
end

app/models/user.rb
require 'digest/sha2'

class User < ApplicationRecord
  SALT = '5d683ac93a'.freeze

  attr_accessor :password, :password_confirmation

  has_many :received_playlists, class_name: 'Playlist', foreign_key: 'for_user_id', dependent: :delete_all, inverse_of: :for_user
  has_many :sent_playlists, class_name: 'Playlist', foreign_key: 'from_user_id', dependent: :nullify, inverse_of: :from_user

  def self.reserved_names
    Rails.application.routes.routes.
        map { |r| r.path.spec.to_s.split('/')[1]&.sub(/\(.+$/, '') }.
        compact.uniq.reject { |p| p.start_with?(':') }
  end

  validates :username,
            presence:  true,
            length:    {maximum: 16},
            format:    {with: /\A[^$&+,\/:;=?@ "<>#%{}|\\\^~\[\]`]+\z/},
            exclusion: {in: reserved_names}
  validates :email,
            email:     true,
            allow_nil: true
  validates :password,
            confirmation: true,
            length:       {minimum: 6},
            exclusion:    {in: %w[123456 password 12345 12345678 qwerty 123456789 1234 baseball dragon football]},
            if:           :password
  validates :password, presence: {on: :create}

  before_validation :encrypt_password, if: :password

  extend SetNilIfBlank
  set_nil_if_blank :email

  def valid_password?(password)
    crypted_password == self.class.encrypt(password)
  end

  def to_param() username end

  # @private
  def self.encrypt(string)
    Digest::SHA256.hexdigest(string + SALT)
  end

  private

  def encrypt_password
    self.crypted_password = self.class.encrypt(password)
  end
end

app/controllers/account/playlists_controller.rb
class Account::PlaylistsController < ApplicationController
  before_action :login_required
  before_action :find_playlist, only: %i[ack like]
  respond_to :json

  def index
    @playlists = if params[:tag].present?
                   Tag.where(name: params[:tag]).joins(playlist: %i[tags]).
                       where(playlists: {for_user_id: current_user.id}) # adding :from_user to this association breaks the SQL query
                 else
                   current_user.received_playlists.includes(:from_user, :tags)
                 end

    @playlists = @playlists.where(playlists: {listened_at: nil, priority: params[:priority]}).
        order('playlists.created_at DESC')

    page = params[:page].to_i
    page = 1 if page < 1

    response.headers['X-Page']  = page.to_s
    response.headers['X-Count'] = @playlists.count.to_s

    @playlists = @playlists.limit(10).offset((page-1)*10)
    @playlists = @playlists.map(&:playlist).uniq if params[:tag].present?

    respond_with @playlists
  end

  def ack
    @playlist.listened_at = @playlist.listened_at ? nil : Time.now
    @playlist.save

    respond_with(@playlist) do |format|
      format.json { render json: {listened_at: @playlist.listened_at} }
    end
  end

  def like
    @playlist.toggle :liked
    @playlist.save

    respond_with(@playlist) do |format|
      format.json { render json: {liked: @playlist.liked} }
    end
  end

  private

  def find_playlist
    @playlist = current_user.received_playlists.find(params[:id])
  end
end

app/controllers/playlists_controller.rb
require 'addressable/uri'

class PlaylistsController < ApplicationController
  def index
    render current_user ? 'index' : 'splash'
  end

  def name
    return render(json: {title: nil}) unless params[:url].present?

    uri  = Addressable::URI.parse(params[:url].strip)
    html = load_url(uri)
    return render(json: {title: nil}) unless html

    title = load_url_title(html)
    return render(json: {title: nil}) unless title

    title = title.strip.gsub(/\s*\n\s*/, ' ')

    title = load_meta_title(html) if title == 'Connecting to the iTunes Store.'

    name = if title =~ /^iTunes - Music - (.+)$/
             Regexp.last_match(1)
           elsif title =~ /^(.+) on iTunes$/
             Regexp.last_match(1)
           elsif title =~ /^(.+) on Apple Music$/
             Regexp.last_match(1)
           elsif title =~ /^(.+) \| Free Listening on SoundCloud$/
             Regexp.last_match(1)
           elsif title =~ /^(.+) [|\-] YouTube$/
             Regexp.last_match(1)
           end

    if (title.include?('iTunes') || title.include?('Apple Music')) && (song_title, _artist, _album = load_song_title(html, uri))
      name = "#{song_title} - #{name}"
    end

    render json: {title: name ? name[0, 100] : nil}
  end

  private

  def load_url(uri)
    return nil unless %(http https).include?(uri.scheme)

    conn = Faraday.new(url: uri.origin, ssl: {verify: false}) do |f|
      f.use FaradayMiddleware::FollowRedirects
      f.adapter Faraday.default_adapter
    end
    res = conn.get(uri.request_uri)
    return nil if !res.status || res.status/100 != 2

    Nokogiri::HTML(res.body)
  end

  def load_url_title(html)
    title = html.css('head title').text
    return nil unless title

    return title.gsub(/\\u\d{4}/) do |escape|
      [escape[2..-1].hex].pack('U')
    end
  end

  def load_song_title(html, uri)
    return unless uri.query_values

    song_id = uri.query_values['i']
    return nil unless song_id

    json = html.css('#shoebox-ember-data-store').first&.content or return nil
    json = JSON.parse(json)

    album_name = json['data']['attributes']['name']

    record = json['included'].detect { |r| r['type'] == 'song' && r['id'].to_s == song_id.to_s } or return nil
    song_name   = record['attributes']['name']
    artist_name = record['attributes']['artistName']
    return song_name, artist_name, album_name
  end

  def load_meta_title(html)
    meta = html.css('meta[property="og:title"]')
    return nil unless meta

    return meta[0].attributes['content'].text
  end
end

app/controllers/user/playlists_controller.rb
class User::PlaylistsController < ApplicationController
  before_action :find_user
  respond_to :html, :json

  def index
    @playlists = if params[:tag].present?
                   Tag.where(name: params[:tag]).joins(playlist: %i[tags]).
                       where(playlists: {for_user_id: @user.id}) # adding :from_user to this association breaks the SQL query
                 else
                   @user.received_playlists.includes(:from_user, :tags)
                 end

    @playlists = @playlists.where(liked: true) if params[:liked].present?

    @playlists = @playlists.where(playlists: {priority: params[:priority]}).
        order('playlists.created_at DESC')

    page = params[:page].to_i
    page = 1 if page < 1

    response.headers['X-Page']  = page.to_s
    response.headers['X-Count'] = @playlists.count.to_s

    @playlists = @playlists.limit(10).offset((page-1)*10)
    @playlists = @playlists.map(&:playlist).uniq if params[:tag].present?

    respond_with @playlists
  end

  def new
    @playlist = @user.sent_playlists.build(from_user: current_user)
    respond_with @playlist
  end

  def create
    @playlist = @user.received_playlists.create(playlist_params.merge(from_user: current_user))
    respond_with @playlist do |format|
      format.html do
        if @playlist.valid?
          render 'create'
        else
          Rails.logger.warn "Playlist errors: #{@playlist.errors.inspect}"
          render 'new'
        end
      end
    end
  end

  private

  def find_user
    @user = User.find_by_username!(params[:user_id])
  end

  def playlist_params
    params.require(:playlist).permit(:url, :name, :description, :priority, :tag_names)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :must_be_unauthenticated
  respond_to :html

  def new
    @user = User.new
    respond_with @user
  end

  def create
    @user = User.create(user_params)
    log_in @user
    respond_with @user, location: (params[:next] || root_url)
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation, :email)
  end
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
  def random_title
    t('helpers.playlists.titles').sample
  end

  def priorities
    t('models.playlist.priorities').map.with_index { |p, i| [p, i] }
  end
end

app/views/user/playlists/create.html.slim
.row
  div
  div
    h1 It’s on the list.

    h2
      = link_to "More?", new_playlist_url
      '  Or
      = link_to "see #{@user.username}’s playlist", playlist_url(@user)

app/views/user/playlists/index.html.slim
.row
  div
  h1
    - if params[:tag].present?
      ' hashtag: #{params[:tag]}
      small= link_to "(clear tag)", playlist_url(@user, tag: nil, liked: params[:liked])
    - else
      | #{@user.username}’s list

    = ' '
    small
      - if params[:liked].present?
        = link_to "(also not liked)", playlist_url(@user, tag: params[:tag])
      - else
        = link_to "(just liked)", playlist_url(@user, tag: params[:tag], liked: 'true')

.row#nothing
  div
  p nothing yet.

- priorities.reverse.each do |(priority_name, priority_number)|
  .playlist-containter data-priority=priority_number data-name=priority_name

app/views/user/playlists/index.js.coffee.erb
updateNoneVisibility = ->
    if $('[data-priority]').text().length == 0
        $('#nothing').show()
    else
        $('#nothing').hide()

$(window).ready ->
    $('[data-priority]').each ->
        new Playlist $(this), "<%= escape_javascript user_playlists_url(@user, tag: params[:tag].presence, liked: params[:liked].presence, priority: 'REPLACEME', format: 'json') %>".replace('REPLACEME', $(this).attr('data-priority')), $(this).attr('data-name'), ->
            updateNoneVisibility()

app/views/user/playlists/new.html.slim
.row
  div
  h1= random_title

= form_with model: @playlist, url: user_playlists_url(@user), method: :post, local: true do |f|
  .row
    div= f.label :url, "link it."
    div= f.url_field :url, required: true, id: 'playlist_url'

  .row
    div= f.label :name, "name it."
    div= f.text_field :name, placeholder: 'optional', maxlength: 100, id: 'playlist_name'

  .row
    div= f.label :priority, "prioritize it."
    div= f.select :priority, priorities, {}, data: {multibutton: true}

  .row
    div= f.label :tag_names, "tag it."
    div= f.text_field :tag_names, placeholder: '#metal #screaming #omgchesterscreaming'

  .row
    div= f.label :description, "describe it."
    div= f.text_area :description, placeholder: 'optional'

  .row
    div
    div= f.submit

app/views/user/playlists/new.js.coffee.erb
$(window).ready ->
    loading = false
    placeholder = $('#playlist_name').attr('placeholder')

    $('#playlist_url').change ->
        if !loading && $('#playlist_url').val().length > 0
            loading = true
            $('#playlist_name').attr 'placeholder', 'guessing a name…'
            $.ajax "<%= escape_javascript guess_name_url %>",
                data: {url: $('#playlist_url').val()}
                dataType: 'json'
                complete: ->
                    loading = false
                    $('#playlist_name').attr 'placeholder', placeholder
                success: (result) ->
                    if $('#playlist_name').val().length == 0
                        $('#playlist_name').val result.title