config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :users, only: %i[new create] do
    resources :playlists, controller: 'user/playlists', only: %i[index create]
  end
  resource :account, only: :destroy do
    resources :playlists, controller: 'account/playlists', only: :index do
      member { patch :ack, :like }
    end
  end
  resource :session, only: %i[new create destroy]

  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  get 'logout' => 'sessions#destroy'

  scope path: '/:user_id' do
    get '' => 'user/playlists#new', as: :new_playlist
    get 'playlist' => 'user/playlists#index'
    get 'playlist/name' => 'playlists#name', as: :guess_name
  end

  root 'playlists#index'
end

app/views/layouts/_inline_js.html.slim
- view_paths.paths.map(&:to_path).each do |path|
  - if (file = Rails.root.join(path, full_controller_path, current_template + '.js')).exist?
    script nonce=content_security_policy_nonce type="text/javascript" == defer_inline_js File.read(file)

  - if (file = Rails.root.join(path, full_controller_path, current_template + '.js.erb')).exist?
    script nonce=content_security_policy_nonce type="text/javascript" == defer_inline_js ERB.new(File.read(file)).result(binding)

  - if (file = Rails.root.join(path, full_controller_path, current_template + '.js.coffee')).exist?
    script nonce=content_security_policy_nonce type="text/javascript" == defer_inline_js CoffeeScript.compile(File.read(file))

  - if (file = Rails.root.join(path, full_controller_path, current_template + '.js.coffee.erb')).exist?
    script nonce=content_security_policy_nonce type="text/javascript" == defer_inline_js CoffeeScript.compile(ERB.new(File.read(file)).result(binding))

= content_for :javascripts

app/views/layouts/_nav.html.slim
nav: ul
  - if logged_in?
    li= link_to "My List", root_url
    li= link_to "Log Out", logout_url
    /li= link_to "Deactivate", account_url, method: :delete
  - else
    li= link_to "Sign In", login_url(next: request.fullpath)
    li= link_to "Join", signup_url(next: request.fullpath)

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta name="description" content="What should I be listening to?"
    meta name="author" content="Tim Morgan"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    = csrf_meta_tags

    title also.

    = stylesheet_link_tag 'application', nonce: content_security_policy_nonce
    = javascript_include_tag 'application', nonce: true, defer: true

    style nonce=content_security_policy_nonce == random_background_image_style

  body class=full_controller_name id="#{full_controller_name}-#{current_template}"
    article
      = render partial: 'layouts/nav'
      = yield

    = render partial: 'layouts/inline_js'